### ISSUE TITLE
I would like to join the Freeplane documentation team if possible.

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/docs#119]
I was on the Freeplane documentation team a few years ago but my activities took me a different direction.  I thought at the time the 2-pane organizer, RightNote, would better suit my needs.  Or, rather, the needs of my associates, who don't speak mindmap at all and don't want to.  Plus some family issues limited my time available to continue on the Freeplane documentation team then.

That has cooled down a bit and I find myself strongly drawn back to Freeplane.

In the 1980's I was involved in developing documentation for a temporary employment agency, documenting a dispatching app - that was until the agency went a different direction.  I wish Freeplane had been around then.

I worked at WordPerfect corporation as a support rep for about 2 years.  Much of that job was to explain the software's functions, in simple terms.  I got good supervisor reviews.  I was in a floating backup team that was assigned to take up slack in all the specific departments (e.g., General Features, Macros, Printing, even PlanPerfect spreadsheet).  I had to quickly grasp lots of pieces of the software (and sometimes took calls without being at a computer).  All that was back in the early 1990's.

I have been retired, for about 15 years, from being a teacher's aid in rural Utah public schools.  Writing is one of my hobbies and I frequently get calls from friends asking me to help with various apps as well as editing requests.

I love Freeplane.  It and my freebie Bible study app, theWord, are my 2 main tools - with an assist from RightNote for producing more traditional stuff that other people are more familiar and comfortable with.

PS : I am not a coder and I don't know much about hardware.

**Comment by kenfhill84083** [comment]
If you are interested, you can seem my youtube channel Freeplane playlist [here](you can see my youtube channel Freeplane playlist here : https://www.youtube.com/playlist?list=PLIyXLRsF5Cdb09v2b4FkA6Ux_Nf6B2I-a

**Comment by dpolivaev** [comment]
You are welcome, I have sent you the invite.
