### ISSUE TITLE
Remove tables of contents from tops of pages?

### ISSUE THREAD

**Issue by 1-DimensionalBox** [freeplane/docs#50]
Tables of contents (TOCs) were also brought up [here](https://github.com/freeplane/docs/discussions/19#discussioncomment-3112278) by dpolivaev.

macmarrum listed three possibilities:

> 1. Maintain a TOC whitlist or a TOC blacklist of page names (in index.html)
> 2. Change the logic to create TOC only if a page contains `<div id="toc"></div>` and add the `div` only to those pages that should have TOC
> 3. Change the way TOC is displayed for all pages: add a "Show/Hide" button next to "Contents" and save the state with cookies/local storage; once hidden on one page, will be hidden on all

A combination of option 1 (a blacklist) and and option 3 was implemented in pull request #39.
\
\
However, I think the website would be more clean without the TOCs on tops of pages. Many pages are currently very short, which I think is a good thing. But this results in TOCs only repeating the name of the page.

Wouldn't it be better to completely move TOCs into the left bar?

Another smaller change would be to have a minimized top TOC to be the standard. But then there's a risk that users never discover it.

**Comment by macmarrum** [comment]
> I think the website would be more clean without the TOCs on tops of pages. Many pages are currently very short, which I think is a good thing. But this results in TOCs only repeating the name of the page.

Please feel free to submit a PR with a list of page names added to `_toc-blacklist.js`.

> Wouldn't it be better to completely move TOCs into the left bar?

Please see https://github.com/freeplane/docs/discussions/19#discussioncomment-3112278
If you can think of a good way, please share your idea.

> Another smaller change would be to have a minimized top TOC to be the standard. But then there's a risk that users never discover it.

I see your point.
