### ISSUE TITLE
Incoorporate 'Scripting! Security considerations' into main documentation

### ISSUE THREAD

**Issue by 1-DimensionalBox** [freeplane/docs#53]
['Scripting! Security considerations'](https://docs.freeplane.org/#/attic/old-mediawiki-content/Scripting!_Security_considerations) is currently part of the attic, but I think it is too important of a document to be stored there.

**Comment by macmarrum** [comment]
Please feel free to review the page's contents and incorporate it into the main docs, removing the old page from `Attic` and re-linking in other pages.

* You can fork the repository, creating your copy under your user on GitHub → https://docs.github.com/en/get-started/quickstart/fork-a-repo
* You will then be able to add content to your repository. Once you are satisfied/ready, you will create a Pull Request to integrate your changes to the main repository → https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
* See also https://github.com/freeplane/docs/blob/main/README.md

**Comment by 1-DimensionalBox** [comment]
[RE macmarrum](https://github.com/freeplane/docs/issues/53#issuecomment-1186764962): Yes, will do! I wrote issues `#51-57` first to chart what I would like to change (so that you can also stop me if you think it's a bad idea).

**Comment by dpolivaev** [comment]
@1-DimensionalBox I must admit I misunderstood your intention to work on the changes until you clarified it. For me, it makes a huge difference if someone wants to put their own effort or only suggests what some others could do.

**Comment by 1-DimensionalBox** [comment]
Okay @dpolivaev, I apologize for not being clear then.

I understand that implementing changes oneself is preferred. At the same time, I thought defining these changes on beforehand would be good, so that we can discuss them already where necessary.

Perhaps we can take this up tomorrow on the community conference tomorrow?
