### ISSUE TITLE
Change with of the entire map

### ISSUE THREAD

**Issue by mhechthz** [freeplane/docs#64]
Is there a way to change the width of a large map? This would look much more "natural" (compared to the current appearence - see image).

![image](https://user-images.githubusercontent.com/37075144/182014756-1e8836de-ad0d-41db-9b56-c1d4afae76f4.png)

**Comment by dpolivaev** [comment]
View->View settings->Outline view

**Comment by dpolivaev** [comment]
Actually, questions should not be posted in "Issues" but in only "Discussions".
Issues are mainly for traceability and for bug reports.

**Comment by dpolivaev** [comment]
And not in this project but only in https://github.com/freeplane/freeplane/discussions
Check this link, it is the only valid place to ask for help.
